# rulebook.yml
---
- name: BigPanda Webhook Rulebook 1
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6000
  rules:
    - name: Demo Part 1 - Execute Assign to BigPanda UUID and Check Pods Playbook
      condition: |
        event.meta.meta.payload.incident is defined and 
        event.meta.payload.incident.resolved == false and 
        event.meta.payload.incident.active == true and 
        event.meta.payload.incident.alerts is selectattr('check', '==', 'Agent Not Receiving Data') and
        event.meta.payload.incident.alerts is not selectattr('check', '==', 'Trace Alert')
      action:
        run_job_template:
          name: "1. Check Pods"
          organization: Default

    - name: Demo Part 2 - Execute Remediation Steps on the Monitoring Agent
      condition: |
        event.meta.payload.incident is defined and 
        event.meta.payload.incident.resolved == false and 
        event.meta.payload.incident.active == true and 
# event.meta.payload.incident.alerts is selectattr('check', '==', 'Trace Alert')
      action:
        run_job_template:
          name: "2. Restart Agent"
          organization: Default

    - name: Demo Part 3 - Execute Cleanup Playbook
      condition: |
        event.meta.payload.incident is defined and 
        event.meta.payload.incident.status == "Critical"
      action:
        run_job_template:
          name: "3. Cleanup"
          organization: Default
    - name: Log Event
      condition: event.meta is defined
      action:
        debug: