# rulebook.yml
---
- name: BigPanda Webhook Rulebook 1
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Demo Part 1 - [STEP-NAME-HERE]
      condition: |
        event.payload.incident is defined and 
        event.payload.incident.resolved == false and 
        event.payload.incident.active == true and 
        (event.payload.incident.alerts |
         is not selectattr('check', 'eq', 'Agent Not Receiving Data') | list | count > 0 and
         is not selectattr('check', 'eq', 'Trace Alert') | list | count == 0)
      action:
        run_playbook:
          name: playbooks/[PLAYBOOK-NAME-HERE].yml
