- name: Receive webhook and post comment to BigPanda
  hosts: localhost
  gather_facts: no
  vars:
    # Example webhook payload (would normally come from your webhook receiver)
    webhook_payload: "{{ lookup('file', 'webhook.json') | from_json }}"

  tasks:
    - name: Extract incident ID from webhook
      set_fact:
        incident_id: "{{ webhook_payload.id }}"

    - name: Get comment from webhook header
      set_fact:
        incident_comment: "{{ lookup('env', 'BP_COMMENT') }}"

    - name: Post comment to BigPanda
      uri:
        url: "https://api.bigpanda.io/resources/v2.0/environments/63bd568809cb331300ffa555/incidents/{{ incident_id }}/comments"
        method: POST
        headers:
          Content-Type: "application/json"
          x-bp-token: "{{ lookup('env', 'BP_SECRET_TOKEN') }}"
        body: "\"{{ incident_comment }}\""
        body_format: json
        return_content: yes
      register: result

    - debug:
        var: result.json
