---
- name: Cleanup After Remediation
  hosts: localhost
  tasks:
    - name: Set Tags - Automation State Successful
      bigpanda.incident.add_tag:
        environment_id: "{{ environment_id }}"
        tag_id: "automation_state"
        tag_value: "Successful"
        incident_id: "{{ incident_id }}"
        api_token: "{{ api_token }}"
        
    - name: Successful Resolution
      bigpanda.incident.resolve:
        environment_id: "{{ environment_id }}"
        incident_id: "{{ incident_id }}"
        resolution_comment: "Automation Successfully Checked and Remediated Incident {{ instance_hosts }}"
        api_token: "{{ api_token }}"
