# playbooks/comment_to_ticket.yml
---
- name: Run Remediation on Monitoring Agent
  hosts: localhost
  tasks:
    - name: Add Comment - Job Started
      bigpanda.incident.comment:
        environment_id: "{{ environment_id }}"
        incident_id: "{{ incident_id }}"
        comment: "Automation job started. Purpose: REMEDIATION"
        api_token: "{{ api_token }}"

    - name: Set Tags - Automation Job URL
      bigpanda.incident.add_tag:
        environment_id: "{{ environment_id }}"      
        tag_id: "automation_job_url"
        tag_value: "{{ automation_job_url }}"
        incident_id: "{{ incident_id }}"
        api_token: "{{ api_token }}"

    - name: Set Tags - Automation Purpose
      bigpanda.incident.add_tag:
        environment_id: "{{ environment_id }}"
        tag_id: "automation_purpose"
        tag_value: "REMEDIATION"
        incident_id: "{{ incident_id }}"
        api_token: "{{ api_token }}"

    - name: Set Tags - Automation Playbook and Job URL
      bigpanda.incident.add_tag:
        environment_id: "{{ environment_id }}"
        tag_id: "automation_playbook"
        tag_value: "{{ playbook_name }} ID{{ execution_id }}"
        incident_id: "{{ incident_id }}"
        api_token: "{{ api_token }}"

    - name: Mock - Restart the monitoring agent
      bigpanda.incident.comment:
        environment_id: "{{ environment_id }}"
        incident_id: "{{ incident_id }}"
        comment: "Restarting the monitoring agent"
        api_token: "{{ api_token }}"

    - name: Successful Resolution
      bigpanda.incident.resolve:
        environment_id: "{{ environment_id }}"
        incident_id: "{{ incident_id }}"
        resolution_comment: "Restarting the monitoring agent"
        api_token: "{{ api_token }}"
