# playbooks/comment_to_ticket.yml
---
- name: Run Remediation on Monitoring Agent
  hosts: localhost
  tasks:
    - name: Add Comment - Job Started
      bigpanda.incident.comment:
        environment_id: "{{ environment_id }}"
        incident_id: "{{ incident_id }}"
        comment: "Automation job started. {{ playbook_name }} ID{{ execution_id }} Purpose: REMEDIATION If you need to see the execution please click here: {{ automation_job_url }}""
        api_token: "{{ api_token }}"

    - name: Set Tags - Automation Purpose
      bigpanda.incident.add_tag:
        environment_id: "{{ environment_id }}"
        tag_id: "automation_purpose"
        tag_value: "REMEDIATION"
        incident_id: "{{ incident_id }}"
        api_token: "{{ api_token }}"

    - name: Set Tags - Automation Playbook, Job URL, and Purpose
      bigpanda.incident.add_tag:
        environment_id: "{{ environment_id }}"
        tag_id: "automation_playbook_1"
        tag_value: "{{ playbook_name }} ID{{ execution_id }}"
        incident_id: "{{ incident_id }}"
        api_token: "{{ api_token }}"

    - name: Set Tags - Automation Job URL
      bigpanda.incident.add_tag:
        environment_id: "{{ environment_id }}"
        tag_id: "automation_job_url_1"
        tag_value: "{{ automation_job_url }}"
        incident_id: "{{ incident_id }}"
        api_token: "{{ api_token }}"

    - name: Mock - Restart the monitoring agent
      bigpanda.incident.comment:
        environment_id: "{{ environment_id }}"
        incident_id: "{{ incident_id }}"
        comment: "Restarting the monitoring agent"
        api_token: "{{ api_token }}"
